name: easter
version: 2.0.1

description: A small Dart package that calculates the date of Easter from 1583 to 4099.
repository: https://github.com/nikolajskov/easter

environment:
  sdk: '>=2.19.0 <4.0.0'

dev_dependencies:
  test: ^1.16.0

topics:
  - date
